version: 2
jobs:
  build:
    docker:
     - image: alpine:3.7
    steps:
      - checkout

      - run:
          name: Update node package manager
          command: 'npm install -g npm@latest'
      
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: 
          name: test
          command: npm run test
